function initSeoManager(){
 const form=document.getElementById('seoForm'),site=document.getElementById('seoSiteSelect'),page=document.getElementById('seoPageSelect');
 if(!form||!site||!page)return;
 const root=form.closest('.admin-content');if(!root)return;root.classList.add('seo-manager-shell');
 const go=(siteId,pageId)=>{const u=new URL(window.location.href);u.searchParams.set('site',siteId);if(pageId)u.searchParams.set('page',pageId);else u.searchParams.delete('page');window.location.assign(u.toString())};
 site.addEventListener('change',()=>go(site.value,null));page.addEventListener('change',()=>go(site.value,page.value));
 if(!root.querySelector('.seo-page-layout')){
  const layout=document.createElement('div');layout.className='seo-page-layout';
  const nav=document.createElement('aside');nav.className='seo-page-list card';nav.innerHTML='<div class="card-body p-3"><div class="fw-bold mb-1">Public Pages / पब्लिक पेज</div><div class="small text-muted mb-3">Quick select / जल्दी चुनें</div><input class="form-control form-control-sm seo-page-search" data-seo-filter placeholder="Search page / पेज खोजें"><div class="seo-page-list-inner"></div><div class="seo-score-box mt-3"><div class="d-flex justify-content-between align-items-center"><span class="small fw-bold">Current SEO score</span><strong data-seo-score>0%</strong></div><div class="progress mt-2"><div class="progress-bar" data-seo-progress style="width:0%"></div></div><ul class="seo-checklist" data-seo-checklist></ul></div></div>';
  const list=nav.querySelector('.seo-page-list-inner');[...page.options].forEach(opt=>{const a=document.createElement('a');a.className='seo-page-item'+(opt.selected?' active':'');const u=new URL(window.location.href);u.searchParams.set('page',opt.value);a.href=u.toString();const parts=opt.text.split(' — ');a.innerHTML='<span class="seo-page-meta"><span class="seo-page-name"></span><span class="seo-page-path"></span></span><span class="seo-page-score">'+(opt.selected?'EDIT':'')+'</span>';a.querySelector('.seo-page-name').textContent=parts[0];a.querySelector('.seo-page-path').textContent=parts.slice(1).join(' — ');list.appendChild(a)});
  form.parentNode.insertBefore(layout,form);layout.appendChild(nav);layout.appendChild(form);
 }
 if(!form.querySelector('.seo-tabs')){
  const tabs=document.createElement('div');tabs.className='seo-tabs mb-3';const mainCol=form.querySelector(':scope > .row > .col-xl-8');const cards=mainCol?[...mainCol.querySelectorAll(':scope > .card')]:[];
  cards.forEach((card,i)=>{card.dataset.seoCardIndex=i;const h=card.querySelector('.card-header h5,.card-header h4,.card-header h3');const b=document.createElement('button');b.type='button';b.className='seo-tab'+(i===0?' active':'');b.textContent=h?.textContent?.trim()||'Section '+(i+1);b.addEventListener('click',()=>{cards.forEach(c=>c.style.display=c.dataset.seoCardIndex===String(i)?'':'none');tabs.querySelectorAll('.seo-tab').forEach(x=>x.classList.toggle('active',x===b))});tabs.appendChild(b)});
  if(cards.length){form.insertBefore(tabs,form.firstElementChild);cards.forEach((c,i)=>{if(i>0)c.style.display='none'})}
 }
 const fields={title:form.querySelector('[name="meta_title"]'),description:form.querySelector('[name="meta_description"]'),keyword:form.querySelector('[name="focus_keyword"]'),canonical:form.querySelector('[name="canonical_url"]'),robots:form.querySelector('[name="robots"]'),ogTitle:form.querySelector('[name="og_title"]'),ogImage:form.querySelector('[name="og_image"]'),twitterTitle:form.querySelector('[name="twitter_title"]'),twitterImage:form.querySelector('[name="twitter_image"]'),schema:form.querySelector('[name="schema_type"]')};
 const scoreBox=root.querySelector('[data-seo-score]'),progress=root.querySelector('[data-seo-progress]'),checklist=root.querySelector('[data-seo-checklist]');const checks=[['title','Meta title'],['description','Meta description'],['keyword','Focus keyword'],['canonical','Canonical URL'],['robots','Robots'],['ogTitle','OG title'],['ogImage','OG image'],['twitterTitle','Twitter title'],['twitterImage','Twitter image'],['schema','Schema type']];
 if(checklist&&checklist.childElementCount===0)checks.forEach(([key,label])=>{const li=document.createElement('li');li.dataset.check=key;li.innerHTML='<span class="seo-check">•</span><span></span>';li.querySelector('span:last-child').textContent=label;checklist.appendChild(li)});
 const update=()=>{let n=0;checks.forEach(([key])=>{if(fields[key]?.value?.trim())n++});const score=Math.round(n/checks.length*100);if(scoreBox)scoreBox.textContent=score+'%';if(progress)progress.style.width=score+'%';checklist?.querySelectorAll('[data-check]').forEach(el=>{const ok=!!fields[el.dataset.check]?.value?.trim();el.classList.toggle('done',ok);const icon=el.querySelector('.seo-check');if(icon)icon.textContent=ok?'✓':'•'})};
 form.querySelectorAll('input,textarea,select').forEach(el=>{el.addEventListener('input',update);el.addEventListener('change',update)});update();
 root.querySelector('[data-seo-filter]')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();root.querySelectorAll('.seo-page-item').forEach(item=>item.style.display=item.textContent.toLowerCase().includes(q)?'':'none')});
 const schema=form.querySelector('[name="schema_json"]');schema?.addEventListener('blur',()=>{if(!schema.value.trim())return;try{JSON.parse(schema.value);schema.classList.remove('is-invalid')}catch(e){schema.classList.add('is-invalid')}});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initSeoManager,{once:true});else initSeoManager();